[package]
name = "matrix"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "server/src/main.rs"

[workspace]
members = ["server"]

[dependencies]
cargo-run-script = "0.2.0"

[package.metadata.scripts]
start-server = "echo test"
