version: "3"

services:
  db-mx:
    container_name: postgres-mx
    image: postgres
    environment:
      POSTGRES_USER: matrix
      POSTGRES_PASSWORD: passwordpassword
      PGDATA: /data/postgres
      POSTGRES_DB: matrix
    volumes:
      - db-mx:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
  minio:
    image: minio/minio:RELEASE.2023-10-25T06-33-25Z
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "root-user"
      MINIO_ROOT_PASSWORD: "root-password"
    command: server /data --console-address :9001
networks:
  db:
    driver: bridge

volumes:
  db-mx:
