version: "3"

services:
  db-matrix:
    image: postgres
    restart: always
    env_file:
      - .env
    container_name: pg-matrix
    ports:
      #      - "127.0.0.1:5432:5432"
      - '5430:5432' # open host for superset purposes
    volumes:
      - ./pgdata-telegramm:/var/lib/postgresql/data
