//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_tariff_plan")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_tariff_plan_id: Uuid,
    pub tariff_plan_id: Uuid,
    pub user_id: Uuid,
    pub created_at: DateTime,
    pub expires_at: DateTime,
    pub tariff_plan_payment_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::tariff_plan::Entity",
        from = "Column::TariffPlanId",
        to = "super::tariff_plan::Column::TariffPlanId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TariffPlan,
    #[sea_orm(
        belongs_to = "super::tariff_plan_payment::Entity",
        from = "Column::TariffPlanPaymentId",
        to = "super::tariff_plan_payment::Column::TariffPlanPaymentId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    TariffPlanPayment,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::tariff_plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TariffPlan.def()
    }
}

impl Related<super::tariff_plan_payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TariffPlanPayment.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
