//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "user_news")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_news_id: Uuid,
    pub news_id: Uuid,
    pub title: String,
    pub payload: String,
    pub img: Option<String>,
    pub created_at: DateTime,
    pub reading_at: Option<DateTime>,
    pub reading_count: i32,
    pub user_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::news::Entity",
        from = "Column::NewsId",
        to = "super::news::Column::NewsId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    News,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::news::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::News.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
