//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use super::sea_orm_active_enums::CalculatorType;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "calculator")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub calculator_id: Uuid,
    #[sea_orm(unique)]
    pub r#type: CalculatorType,
    pub require_params: Option<Vec<String>>,
    pub options_params: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
