//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod newsletter;
pub mod notify;
pub mod sea_orm_active_enums;
pub mod tariff_plan;
pub mod user_info;
pub mod user_tariff_plan;
pub mod users;
