//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub mod prelude;

pub mod calculator;
pub mod news;
pub mod news_like;
pub mod newsletter;
pub mod notify;
pub mod offer;
pub mod offer_like;
pub mod payment;
pub mod sea_orm_active_enums;
pub mod tariff_plan;
pub mod tariff_plan_payment;
pub mod user_calc_result;
pub mod user_info;
pub mod user_news;
pub mod user_tariff_plan;
pub mod users;
