//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "news")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub news_id: Uuid,
    pub title: String,
    pub payload: String,
    pub is_publish: bool,
    pub img: Option<String>,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::user_news::Entity")]
    UserNews,
}

impl Related<super::user_news::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserNews.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
