//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "newsletter")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub newsletter_id: Uuid,
    pub title: String,
    pub is_published: bool,
    pub payload: String,
    pub created_at: DateTime,
    pub publish_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
