//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::newsletter::Entity as Newsletter;
pub use super::notify::Entity as Notify;
pub use super::user_info::Entity as UserInfo;
pub use super::users::Entity as Users;
