//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15
use async_graphql::*;

use sea_orm::entity::prelude::*;

#[derive(Enum, Copy, Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "user_role_type")]
pub enum UserRoleType {
    #[sea_orm(string_value = "ADMIN")]
    Admin,
    #[sea_orm(string_value = "MEMBER")]
    Member,
    #[sea_orm(string_value = "OWNER")]
    Owner,
}
