//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tariff_plan_payment")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub tariff_plan_payment_id: Uuid,
    pub user_id: Uuid,
    pub payment_id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::payment::Entity",
        from = "Column::PaymentId",
        to = "super::payment::Column::PaymentId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Payment,
    #[sea_orm(has_many = "super::user_tariff_plan::Entity")]
    UserTariffPlan,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::UserId",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::payment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Payment.def()
    }
}

impl Related<super::user_tariff_plan::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserTariffPlan.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
