[package]
name = "matrix"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix = "0.13.0"
actix-web = "4"
actix-files = "0.6.6"
chrono = "0.4.22"
diesel = { version = "2.2.0", features = [
  "postgres",
  "uuid",
  "r2d2",
  "chrono",
] }
serde = { version = "1.0.145", features = ["derive"] }
serde_json = "1.0.86"
include_dir = "0.6"
mime_guess = "2.0.4"
dotenv = "0.15.0"
