pub mod types;
#[path = "./gql_models/user_calc_result_gql_model.rs"]
pub mod user_calc_result_gql_model;
#[path = "./gql_models/user_calc_result_gql_model.rs"]
pub mod user_calc_result_repository;
pub mod user_gql;
#[path = "./gql_models/user_gql_model.rs"]
pub mod user_gql_model;
pub mod user_info_gql;
#[path = "./gql_models/user_info_gql_model.rs"]
pub mod user_info_gql_model;
#[path = "./repositoryes/user_info_repository.rs"]
pub mod user_info_repository;
#[path = "./services/user_info_service.rs"]
pub mod user_info_service;
pub mod user_news_gql;
#[path = "./gql_models/user_news_gql_model.rs"]
pub mod user_news_gql_model;
#[path = "./repositoryes/user_news_repository.rs"]
pub mod user_news_repository;
#[path = "./services/user_news_service.rs"]
pub mod user_news_service;
#[path = "./repositoryes/user_repository.rs"]
pub mod user_repository;
#[path = "./services/user_service.rs"]
pub mod user_service;
pub mod user_tariff_plan_gql;
#[path = "./gql_models/user_tariff_plan_gql_model.rs"]
pub mod user_tariff_plan_gql_model;
#[path = "./repositoryes/user_tariff_plan_repository.rs"]
pub mod user_tariff_plan_repository;
#[path = "./services/user_tariff_plan_service.rs"]
pub mod user_tariff_plan_service;
